spring:
  application:
    name: emprestimo_app
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
    show-sql: true  
  datasource:
    username: root
    password: SQLPass2023
    url: jdbc:mysql://localhost:3306/apirest
          